#!/usr/bin/php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('COMPOSER_AUTOLOAD_PATH', $file);
        break;
    }
}

unset($file);

if (!defined('COMPOSER_AUTOLOAD_PATH')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    die(1);
}

require COMPOSER_AUTOLOAD_PATH;

$console = new \Symfony\Component\Console\Application('flatbase');
$console->add(new \Flatbase\Console\Commands\ReadCommand());
$console->run();